"""Command-line entry point."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml
from dotenv import load_dotenv

from .knob_loader import all_knob_paths, load_knob_registry, parse_overrides
from .runner import generate
from .validate import validate

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_CONFIG_DIR = REPO_ROOT / "configs"

# Auto-load .env at repo root if present. Existing env vars take precedence
# (override=False) so shell-set ACN_API_TOKEN beats .env file.
load_dotenv(REPO_ROOT / ".env", override=False)


def cmd_generate(args: argparse.Namespace) -> int:
    cli_overrides = parse_overrides(args.override or [])
    manifest = generate(
        scenario_id=args.scenario,
        seed=args.seed,
        output_dir=Path(args.output_dir),
        config_dir=Path(args.config_dir),
        cli_overrides=cli_overrides,
        noise_profile_override=args.noise_profile,
    )
    print(f"generated {manifest['scenario_id']} seed={manifest['seed']} -> {args.output_dir}")
    # Auto-validate only when no perturbation was actually applied. Per-jitter
    # knobs are authoritative — checking profile name alone misses cases where
    # the user overrode individual jitters under a clean profile (or vice
    # versa). Run `cli validate <dir>` explicitly for noisy outputs.
    if _all_jitters_zero(manifest):
        rep = validate(Path(args.output_dir), strict=False)
        if not rep.passed:
            print("VALIDATION FAILED:", file=sys.stderr)
            for e in rep.errors:
                print(f"  - {e}", file=sys.stderr)
            return 1
        if rep.warnings:
            for w in rep.warnings:
                print(f"  warning: {w}", file=sys.stderr)
    return 0


_JITTER_KNOBS = (
    "noise.building_load_jitter_pct",
    "noise.arrival_time_jitter_min",
    "noise.soc_arrival_jitter_pct",
    "noise.dr_notification_dropout_prob",
    "noise.price_jitter_pct",
    "noise.occupancy_jitter_pct",
)


def _all_jitters_zero(manifest: dict) -> bool:
    res = manifest.get("knob_resolution", {})
    for k in _JITTER_KNOBS:
        entry = res.get(k)
        if entry is None:
            continue
        if float(entry["value"]) != 0.0:
            return False
    return True


def cmd_validate(args: argparse.Namespace) -> int:
    rep = validate(Path(args.output_dir), strict=args.strict)
    if rep.errors:
        print("VALIDATION FAILED:", file=sys.stderr)
        for e in rep.errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    if rep.warnings:
        for w in rep.warnings:
            print(f"  warning: {w}", file=sys.stderr)
    print("OK")
    return 0


def cmd_list_knobs(args: argparse.Namespace) -> int:
    reg = load_knob_registry(Path(args.config_dir) / "knobs.yaml")
    for path in all_knob_paths(reg):
        spec = reg[path]
        typ = spec.get("type", "?")
        default = spec.get("default")
        print(f"{path:55s}  type={typ:18s}  default={default!r}")
    return 0


def cmd_list_scenarios(args: argparse.Namespace) -> int:
    sdir = Path(args.config_dir) / "scenarios"
    for f in sorted(sdir.glob("*.yaml")):
        with f.open() as fh:
            sc = yaml.safe_load(fh)
        print(f"{sc['scenario_id']:8s}  {sc.get('description', '')}")
    return 0


def cmd_calibrate(args: argparse.Namespace) -> int:
    from .calibration import calibrate_populations

    pops_path = Path(args.config_dir) / "populations.yaml"
    pops = args.population if args.population else None
    population_names = [pops] if pops else None
    sites = tuple(args.site) if args.site else ("caltech", "jpl", "office001")
    summary = calibrate_populations(
        populations_yaml_path=pops_path,
        population_names=population_names,
        sites=sites,
        year_start=args.year_start,
        year_end=args.year_end,
        cache_dir=Path(args.cache_dir),
        artifact_dir=Path(args.artifact_dir),
    )
    print(f"calibration complete: {summary['provenance']}")
    print(f"  n_users={summary['n_users_total']}  n_sessions={summary['n_sessions_total']}")
    print(f"  capacity_inference_fallback_rate={summary['capacity_inference_fallback_rate']:.3f}")
    for pop_name, pop_summary in summary["populations"].items():
        regions = pop_summary.get("regions", [])
        print(f"  {pop_name}: {len(regions)} regions fit "
              f"unassigned_rate={pop_summary['unassigned_user_rate']:.3f}")
    return 0


def cmd_docs_gen(args: argparse.Namespace) -> int:
    """Emit the auto-generated section of KNOB_REFERENCE.md to stdout."""
    from .knob_loader import (
        DEEP_OVERRIDE_PREFIXES,
        DIST_PARAM_RANGES,
        all_knob_paths,
        load_knob_registry,
    )

    out: list[str] = []
    out.append("# KNOB_REFERENCE — auto-generated\n")
    out.append("> Generated by `v2b-syndata docs-gen`. Do not edit by hand;\n"
               "> the hand-written usage guide section follows the auto block.\n")
    out.append("## Override path syntax\n")
    out.append("Two channels:\n")
    out.append("- **Registry channel**: `bucket.knob` paths declared in `configs/knobs.yaml`.\n")
    out.append("- **Deep channel**: paths under one of the prefixes below; values flow into\n"
               "  the population's `region_distributions` overlay block at resolve time.\n")

    out.append("## Source categories\n")
    out.append("Each resolved knob carries one of:\n")
    out.append("- `explicit` — set via `--override` or scenario YAML.\n")
    out.append("- `descriptor:<name>` — supplied by a Tier-0 descriptor expansion.\n")
    out.append("- `calibration:<provenance>` — supplied by an ACN-Data calibration run\n"
               "  (e.g. `calibration:acn_data_2019_2021_20260506`).\n")
    out.append("- `default` — fell through all chains; used `knobs.yaml::default`.\n")

    out.append("## Deep-channel parameter ranges\n")
    for prefix, ranges in DEEP_OVERRIDE_PREFIXES.items():
        out.append(f"\n### `{prefix}.<region>.<dist>.<param>`\n")
        out.append("| leaf (`<dist>.<param>`) | range |\n")
        out.append("|---|---|\n")
        for leaf, (lo, hi) in ranges.items():
            out.append(f"| `{leaf}` | `[{lo}, {hi}]` |\n")

    reg = load_knob_registry(Path(args.config_dir) / "knobs.yaml")
    out.append("\n## Registry knobs\n")
    out.append("| path | type | default | range / choices |\n")
    out.append("|---|---|---|---|\n")
    for path in all_knob_paths(reg):
        spec = reg[path]
        typ = spec.get("type", "?")
        default = spec.get("default")
        rng = spec.get("range") or spec.get("choices") or ""
        out.append(f"| `{path}` | `{typ}` | `{default!r}` | `{rng}` |\n")

    print("".join(out))
    _ = DIST_PARAM_RANGES  # silence unused-import warning when ruff strict
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="v2b_syndata", description="V2B synthetic dataset generator")
    p.add_argument("--config-dir", default=str(DEFAULT_CONFIG_DIR),
                   help=f"directory containing knobs.yaml + descriptor libraries (default: {DEFAULT_CONFIG_DIR})")
    sub = p.add_subparsers(dest="command", required=True)

    g = sub.add_parser("generate", help="generate one scenario seed")
    g.add_argument("--scenario", required=True)
    g.add_argument("--seed", type=int, required=True)
    g.add_argument("--output-dir", required=True)
    g.add_argument("--override", action="append", default=[],
                   help="knob override 'bucket.knob=value' (repeatable). YAML-parsed.")
    g.add_argument("--noise-profile", default=None,
                   help="override scenario's noise descriptor")
    g.set_defaults(func=cmd_generate)

    v = sub.add_parser("validate", help="validate an output directory")
    v.add_argument("output_dir")
    v.add_argument("--strict", action="store_true",
                   help="treat soft warnings as hard errors")
    v.set_defaults(func=cmd_validate)

    lk = sub.add_parser("list-knobs")
    lk.set_defaults(func=cmd_list_knobs)

    ls = sub.add_parser("list-scenarios")
    ls.set_defaults(func=cmd_list_scenarios)

    cal = sub.add_parser("calibrate", help="fit per-region distributions from ACN-Data")
    cal.add_argument("--population", default=None,
                     help="single population name to calibrate (default: all populations)")
    cal.add_argument("--year-start", type=int, default=2019)
    cal.add_argument("--year-end", type=int, default=2021)
    cal.add_argument("--site", action="append", default=None,
                     help="ACN-Data site (repeatable; default: caltech jpl office001)")
    cal.add_argument("--cache-dir", default=str(REPO_ROOT / "data" / "calibration" / "acn_cache"))
    cal.add_argument("--artifact-dir", default=str(REPO_ROOT / "data" / "calibration"))
    cal.set_defaults(func=cmd_calibrate)

    dg = sub.add_parser("docs-gen", help="emit auto-generated section of KNOB_REFERENCE.md")
    dg.set_defaults(func=cmd_docs_gen)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
