"""Multi-building generation + optimus-compatible export driver.

Generates N *distinct* buildings in one run — each its own base scenario,
descriptor picks, knob overrides, and seed — and writes them in the
`optimus-persist-multi` CSV schema (see `export_optimus`). Two layouts:

- **shared** (default): one set of CSVs per file, concatenated across buildings
  with a `building_id` column.
- **per-building**: numbered subfolders `<output_dir>/<building_id>/`, each a
  complete single-building set (matching the reference folder exactly).

DR is global: a single unified `dso_commands.csv` is emitted from the first
building's DR events + the global program/incentive/penalty.

The run is exactly reproducible: each building is generated by the
bitwise-deterministic `runner.generate`, and `multi_building_config.json`
records the ordered specs + seeds + globals so `regenerate_from_config`
reproduces byte-identical CSVs.
"""
from __future__ import annotations

import copy
import json
import shutil
import tempfile
import time
import traceback
import uuid
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

from . import __version__
from . import export_optimus as exp
from .batch import BatchResult, _months_between, _record_result, _write_manifest
from .manifest import CSV_NAMES, _git_sha
from .runner import generate

# Optimus per-building files (order is the on-disk write order).
_PER_BUILDING_FILES = [
    "building_load.csv", "cars.csv", "chargers.csv", "sessions.csv",
    "grid_prices.csv", "weather_data.csv", "occupancy.csv",
]
_DEFAULT_POLICY = "ILP-MPCFIXEDFSL"


@dataclass
class BuildingSpec:
    """One building's full configuration."""
    base_scenario: str
    descriptors: dict[str, str] = field(default_factory=dict)
    overrides: dict[str, Any] = field(default_factory=dict)
    seed: int = 42
    noise_profile: str | None = None
    policy: str | None = None  # falls back to MultiConfig.default_policy


@dataclass
class MultiConfig:
    """Globals shared across all buildings in a multi-building run."""
    buildings: list[BuildingSpec]
    output_mode: str = "shared"          # "shared" | "per-building"
    dr_program: str | None = None        # global DR program override (e.g. "CBP")
    dr_incentive_per_kw: float | None = None
    dr_penalty_per_kwh: float | None = None
    default_policy: str = _DEFAULT_POLICY


def _flat_knobs(manifest: dict) -> dict[str, Any]:
    return {p: e["value"] for p, e in manifest.get("knob_resolution", {}).items()}


def _dr_overrides(cfg: MultiConfig) -> dict[str, Any]:
    """Global DR knob overrides applied to every building (so DR is uniform)."""
    ov: dict[str, Any] = {}
    if cfg.dr_program is not None:
        ov["utility_rate.dr_program"] = cfg.dr_program
    if cfg.dr_incentive_per_kw is not None:
        ov["utility_rate.dr_incentive_per_kw"] = cfg.dr_incentive_per_kw
    if cfg.dr_penalty_per_kwh is not None:
        ov["utility_rate.dr_penalty_per_kwh"] = cfg.dr_penalty_per_kwh
    return ov


def _read_native(run_dir: Path) -> dict[str, pd.DataFrame]:
    return {
        f"{name}.csv": pd.read_csv(run_dir / f"{name}.csv")
        for name in CSV_NAMES
    }


def _build_building_tables(
    native: dict[str, pd.DataFrame], knobs: dict[str, Any], building_id: int
) -> dict[str, pd.DataFrame]:
    """All per-building optimus tables (not the global dso_commands/policies)."""
    bl = native["building_load.csv"]
    dt = pd.to_datetime(bl["datetime"])
    sim_start = dt.iloc[0]
    sim_end = dt.iloc[-1] + pd.Timedelta(seconds=exp._TICK_SECONDS)
    return {
        "building_load.csv": exp.build_building_load(bl, building_id),
        "cars.csv": exp.build_cars(
            native["cars.csv"], native["users.csv"], native["sessions.csv"],
            building_id,
        ),
        "chargers.csv": exp.build_chargers(native["chargers.csv"], building_id),
        "sessions.csv": exp.build_sessions(native["sessions.csv"], building_id),
        "grid_prices.csv": exp.build_grid_prices(native["grid_prices.csv"], building_id),
        "weather_data.csv": exp.build_weather(
            str(knobs["building_load.tmyx_station"]), sim_start, sim_end, building_id,
        ),
        "occupancy.csv": exp.build_occupancy(
            str(knobs["building_load.occupancy_source"]), int(sim_start.year), building_id,
        ),
    }


def _write_table(df: pd.DataFrame, path: Path, name: str) -> None:
    df.to_csv(path, index=(name in exp.INDEX_COL_FILES), lineterminator="\n")


def generate_multi(
    cfg: MultiConfig,
    output_dir: Path,
    config_dir: Path,
) -> dict[str, Any]:
    """Generate all buildings and write optimus CSVs. Returns the config dict
    (also written to `multi_building_config.json`)."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    if cfg.output_mode not in ("shared", "per-building"):
        raise ValueError(f"unknown output_mode {cfg.output_mode!r}")

    dr_ov = _dr_overrides(cfg)
    per_building: list[dict[str, pd.DataFrame]] = []
    policies: list[tuple[int, str]] = []
    dso_commands: pd.DataFrame | None = None
    manifests: list[dict] = []

    for bid, spec in enumerate(cfg.buildings):
        overrides = {**spec.overrides, **dr_ov}  # global DR wins
        with tempfile.TemporaryDirectory(prefix="v2b_mb_") as tmp:
            run_dir = Path(tmp)
            manifest = generate(
                scenario_id=spec.base_scenario,
                seed=spec.seed,
                output_dir=run_dir,
                config_dir=Path(config_dir),
                cli_overrides=overrides,
                noise_profile_override=spec.noise_profile,
                descriptor_overrides=spec.descriptors,
            )
            native = _read_native(run_dir)
        knobs = _flat_knobs(manifest)
        per_building.append(_build_building_tables(native, knobs, bid))
        policies.append((bid, spec.policy or cfg.default_policy))
        manifests.append(manifest)

        # Global DR sourced from the FIRST building (DR is run-global).
        if bid == 0:
            dso_commands = exp.build_dso_commands(
                native["dr_events.csv"],
                program=str(knobs.get("utility_rate.dr_program", "none")),
                incentive=float(knobs.get("utility_rate.dr_incentive_per_kw", 0.0)),
                penalty=float(knobs.get("utility_rate.dr_penalty_per_kwh", 0.0)),
            )

    assert dso_commands is not None
    policies_df = exp.build_policies(policies)

    if cfg.output_mode == "shared":
        for name in _PER_BUILDING_FILES:
            merged = pd.concat(
                [tbl[name] for tbl in per_building], ignore_index=True
            )
            _write_table(merged, output_dir / name, name)
        dso_commands.to_csv(output_dir / "dso_commands.csv", index=False,
                            lineterminator="\n")
        policies_df.to_csv(output_dir / "policies.csv", index=False,
                           lineterminator="\n")
    else:  # per-building
        for bid, tables in enumerate(per_building):
            sub = output_dir / str(bid)
            sub.mkdir(parents=True, exist_ok=True)
            for name in _PER_BUILDING_FILES:
                df = tables[name]
                # weather/occupancy match the reference exactly (no building_id).
                if name in exp.WEATHER_OCCUPANCY and "building_id" in df.columns:
                    df = df.drop(columns=["building_id"])
                _write_table(df, sub / name, name)
            dso_commands.to_csv(sub / "dso_commands.csv", index=False,
                                lineterminator="\n")
            exp.build_policies([(bid, cfg.buildings[bid].policy or cfg.default_policy)]
                               ).to_csv(sub / "policies.csv", index=False,
                                        lineterminator="\n")

    config = _config_dict(cfg)
    (output_dir / "multi_building_config.json").write_text(
        json.dumps(config, indent=2, sort_keys=True) + "\n"
    )
    return config


def _config_dict(cfg: MultiConfig) -> dict[str, Any]:
    return {
        "generator_version": __version__,
        "generator_git_sha": _git_sha(),
        "output_mode": cfg.output_mode,
        "globals": {
            "dr_program": cfg.dr_program,
            "dr_incentive_per_kw": cfg.dr_incentive_per_kw,
            "dr_penalty_per_kwh": cfg.dr_penalty_per_kwh,
            "default_policy": cfg.default_policy,
        },
        "buildings": [
            {"building_id": i, **asdict(spec)}
            for i, spec in enumerate(cfg.buildings)
        ],
    }


def config_from_dict(data: dict[str, Any]) -> MultiConfig:
    """Rebuild a MultiConfig from parsed JSON/YAML.

    Accepts both shapes: an exported `multi_building_config.json` (globals
    nested under `"globals"`) and a hand-authored config (globals at top level).
    """
    g = data.get("globals", data)  # nested (exported) or top-level (authored)
    specs = []
    for b in data["buildings"]:
        specs.append(BuildingSpec(
            base_scenario=b["base_scenario"],
            descriptors=b.get("descriptors") or {},
            overrides=b.get("overrides") or {},
            seed=int(b.get("seed", 42)),
            noise_profile=b.get("noise_profile"),
            policy=b.get("policy"),
        ))
    return MultiConfig(
        buildings=specs,
        output_mode=data.get("output_mode", g.get("output_mode", "shared")),
        dr_program=g.get("dr_program"),
        dr_incentive_per_kw=g.get("dr_incentive_per_kw"),
        dr_penalty_per_kwh=g.get("dr_penalty_per_kwh"),
        default_policy=g.get("default_policy", _DEFAULT_POLICY),
    )


def regenerate_from_config(
    config_path: Path, output_dir: Path, config_dir: Path
) -> dict[str, Any]:
    """Reproduce a prior multi-building run from its `multi_building_config.json`."""
    data = json.loads(Path(config_path).read_text())
    cfg = config_from_dict(data)
    return generate_multi(cfg, output_dir, config_dir)


# ─────────────────────────────────────────────────────────────────────────────
# Unified batch: buildings × samples × months
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class _MultiUnitSpec:
    """One (month, sample) generation unit for the multi-building batch."""
    cfg: MultiConfig
    month_label: str          # e.g. "APR2024"
    sample_idx: int
    seed: int                 # representative seed (for the manifest log)
    unit_dir: Path            # <output_dir>/<MONTH>/<sample>/
    config_dir: Path


def _unit_config(
    base: MultiConfig, month_iso: str, sample: int, noise_profile: str | None,
    seed_base: int,
) -> MultiConfig:
    """Clone the base config for one (month, sample): pin the month window, the
    per-sample seed offset, and the per-sample noise on every building."""
    cfg = copy.deepcopy(base)
    for spec in cfg.buildings:
        spec.overrides = dict(spec.overrides)
        spec.overrides["sim_window.mode"] = "month"
        spec.overrides["sim_window.start"] = month_iso
        # Per-building noise wins; the batch-level noise_profile is the default
        # for buildings that didn't set their own.
        eff_noise = spec.noise_profile or noise_profile
        # Seed-varying batch: tmyx_stochastic adds Dirichlet noise per batch.py.
        if eff_noise == "tmyx_stochastic":
            spec.overrides.setdefault(
                "user_behavior.axes_distribution_dirichlet_alpha", 30.0)
            spec.overrides.setdefault("ev_fleet.battery_mix_dirichlet_alpha", 30.0)
        spec.noise_profile = eff_noise
        spec.seed = spec.seed + seed_base + sample
    return cfg


def _run_one_multi_unit(spec: _MultiUnitSpec) -> BatchResult:
    """Worker: generate one (month, sample) multi-building optimus set."""
    t0 = time.monotonic()
    try:
        generate_multi(spec.cfg, spec.unit_dir, spec.config_dir)
        status, err = "succeeded", None
    except Exception as e:  # noqa: BLE001
        status = "failed"
        err = f"{type(e).__name__}: {e}\n{traceback.format_exc()}"[-2000:]
    return BatchResult(
        month=spec.month_label, sample_idx=spec.sample_idx, seed=spec.seed,
        path=f"{spec.month_label}/{spec.sample_idx}", status=status,
        duration_sec=time.monotonic() - t0, error=err,
    )


def generate_multi_batch(
    cfg: MultiConfig,
    output_dir: Path,
    config_dir: Path,
    start_month: str,
    end_month: str,
    samples_per_month: int,
    *,
    seed_base: int = 0,
    workers: int = 4,
    noise_profile: str | None = "tmyx_stochastic",
    force: bool = False,
    progress_callback=None,
) -> dict[str, Any]:
    """Generate buildings × samples × months → optimus CSVs in a batch tree.

    Layout `<output_dir>/<MONTH>/<sample>/` (each a shared or per-building
    optimus set with a `building_id` column). Mirrors `batch.run_batch`:
    ProcessPool over (month, sample) units, a `batch_manifest.json` of the same
    shape (+ `n_buildings`/`output_mode`), and per-sample-completion progress.
    Each building's seed for a unit is `building.seed + seed_base + sample`.
    """
    output_dir = Path(output_dir)
    if output_dir.exists():
        if not force:
            raise FileExistsError(
                f"Output dir {output_dir} exists. Pass force=True to overwrite.")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    months = _months_between(start_month, end_month)
    specs: list[_MultiUnitSpec] = []
    for label, dt in months:
        iso = dt.strftime("%Y-%m-%d")
        for s in range(samples_per_month):
            specs.append(_MultiUnitSpec(
                cfg=_unit_config(cfg, iso, s, noise_profile, seed_base),
                month_label=label, sample_idx=s, seed=seed_base + s,
                unit_dir=output_dir / label / str(s), config_dir=Path(config_dir),
            ))

    batch_id = f"{int(time.time())}_{uuid.uuid4().hex[:6]}"
    manifest: dict[str, Any] = {
        "batch_id": batch_id,
        "kind": "multi_building",
        "n_buildings": len(cfg.buildings),
        "output_mode": cfg.output_mode,
        "start_month": start_month,
        "end_month": end_month,
        "samples_per_month": samples_per_month,
        "seed_base": seed_base,
        "seed_strategy": "building.seed + seed_base + sample",
        "noise_profile": noise_profile,
        "workers": workers,
        "started_at": datetime.utcnow().isoformat() + "Z",
        "completed_at": None,
        "status": "in_progress",
        "n_total": len(specs),
        "n_succeeded": 0,
        "n_failed": 0,
        "samples": [],
    }
    manifest_path = output_dir / "batch_manifest.json"
    _write_manifest(manifest_path, manifest)

    results: list[BatchResult] = []
    use_parallel = workers > 1 and len(specs) > 1
    if use_parallel:
        try:
            with ProcessPoolExecutor(max_workers=workers) as pool:
                futures = {pool.submit(_run_one_multi_unit, s): s for s in specs}
                for fut in as_completed(futures):
                    res = fut.result()
                    results.append(res)
                    _record_result(manifest, res)
                    _write_manifest(manifest_path, manifest)
                    if progress_callback:
                        progress_callback(res, manifest)
        except Exception as e:  # noqa: BLE001
            manifest["parallel_fallback_reason"] = f"{type(e).__name__}: {e}"
            use_parallel = False
            done = {(r.month, r.sample_idx) for r in results}
            for s in specs:
                if (s.month_label, s.sample_idx) in done:
                    continue
                res = _run_one_multi_unit(s)
                results.append(res)
                _record_result(manifest, res)
                _write_manifest(manifest_path, manifest)
                if progress_callback:
                    progress_callback(res, manifest)
    else:
        for s in specs:
            res = _run_one_multi_unit(s)
            results.append(res)
            _record_result(manifest, res)
            _write_manifest(manifest_path, manifest)
            if progress_callback:
                progress_callback(res, manifest)

    manifest["completed_at"] = datetime.utcnow().isoformat() + "Z"
    failed = manifest["n_failed"]
    if failed == 0:
        manifest["status"] = "succeeded"
    elif failed > len(specs) // 2:
        manifest["status"] = "failed"
    else:
        manifest["status"] = "partial"
    manifest["samples"].sort(key=lambda r: (r["month"], r["sample_idx"]))
    _write_manifest(manifest_path, manifest)
    return manifest
