#!/usr/bin/env python3
"""Generate the data-driven appendix sections of the KDD paper.

Emits four \\input-able LaTeX files under paper/sections/, each built ONLY
from committed artifacts so the numbers cannot drift from the evidence:

  appendix_fits.tex    docs/experiments/s1_fidelity_cis.csv (KS/W1 + 95% CIs)
                       + S1 moments, S2 copula, S3 held-out tables parsed from
                       docs/CALIBRATION_RESULTS.md (auto-generated doc)
  appendix_corpus.tex  configs/campus_10.yaml + the ten
                       data/output/campus10/b*/batch_manifest.json files
  appendix_tstr.tex    data/tstr/results.json + results_elaadnl_matched.json
                       (harness details from tools/tstr_forecasting.py)
  appendix_axes.tex    configs/populations.yaml region-box geometries

Usage:  uv run python tools/gen_paper_appendix.py
Rerun after regenerating any of the upstream artifacts. paper/ is untracked;
this script only (over)writes the four files above.
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SECTIONS = REPO / "paper" / "sections"
CAL_MD = REPO / "docs" / "CALIBRATION_RESULTS.md"
CIS_CSV = REPO / "docs" / "experiments" / "s1_fidelity_cis.csv"
CAMPUS_YAML = REPO / "configs" / "campus_10.yaml"
CAMPUS_DIR = REPO / "data" / "output" / "campus10"
TSTR_DIR = REPO / "data" / "tstr"
POPS_YAML = REPO / "configs" / "populations.yaml"

HEADER = "%% AUTO-GENERATED by tools/gen_paper_appendix.py — do not hand-edit.\n"


def esc(s: str) -> str:
    """Escape LaTeX specials in identifiers (underscores, percent, ampersand)."""
    return (str(s).replace("\\", r"\textbackslash{}").replace("_", r"\_")
            .replace("%", r"\%").replace("&", r"\&").replace("#", r"\#"))


def md_table_rows(md: str, section_header: str) -> list[list[str]]:
    """Return the data rows of the first pipe table after `section_header`."""
    idx = md.index(section_header)
    rows: list[list[str]] = []
    in_table = False
    for line in md[idx:].splitlines():
        stripped = line.strip()
        if stripped.startswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= {"-", ":", " "} for c in cells):  # separator
                in_table = True
                continue
            if in_table:
                rows.append(cells)
        elif in_table:
            break
    return rows


# --------------------------------------------------------------------------- #
# 1. appendix_fits.tex
# --------------------------------------------------------------------------- #
def gen_fits() -> None:
    md = CAL_MD.read_text()

    # -- join the CI CSV with the S1 moments from the markdown table --------- #
    with CIS_CSV.open() as fh:
        cis = {(r["source"], r["region"], r["variable"]): r
               for r in csv.DictReader(fh)}

    s1_md = {}
    for cells in md_table_rows(md, "## S1"):
        src, region, var = cells[0], cells[1].replace(" ", "_"), cells[2].replace(" ", "_")
        s1_md[(src, region, var)] = {
            "src_musig": cells[5], "gen_musig": cells[6], "dmu": cells[7]}

    s1_rows = []
    for key, r in cis.items():
        m = s1_md.get(key)
        if m is None:
            raise SystemExit(f"S1 cell {key} in CSV but not in CALIBRATION_RESULTS.md")
        src, region, var = key
        s1_rows.append(
            f"{esc(src)} & {esc(region.replace('_', ' '))} & "
            f"{var.split('_')[0]} & "
            f"{int(r['n_source']):,} & {int(r['n_generated']):,} & "
            f"{m['src_musig']} & {m['gen_musig']} & {m['dmu']} & "
            f"{float(r['ks_statistic']):.3f} & "
            f"[{float(r['ks_ci_lo']):.3f}, {float(r['ks_ci_hi']):.3f}] & "
            f"{float(r['wasserstein_1']):.2f} & "
            f"[{float(r['w1_ci_lo']):.2f}, {float(r['w1_ci_hi']):.2f}] \\\\")

    # -- S2 copula table ------------------------------------------------------ #
    s2_rows = []
    for c in md_table_rows(md, "## S2"):
        s2_rows.append(f"{esc(c[0])} & {c[1]} & {c[2]} & {c[3]} & {c[4]} & {c[5]} \\\\")

    # -- S3 held-out table ----------------------------------------------------- #
    s3_rows = []
    for c in md_table_rows(md, "## S3"):
        delta = c[9]
        dval = float(delta.replace("+", ""))
        dcell = f"$\\mathbf{{{delta}}}$" if dval >= 0.19 else f"${delta}$"
        fam_refit, fam_ship = c[5], c[6]
        mismatch = r"\,$\dagger$" if fam_refit != fam_ship else ""
        s3_rows.append(
            f"{esc(c[0])} & {c[1]} & {c[2].split(' ')[0]} & {c[3]} & {c[4]} & "
            f"{fam_refit}{mismatch} & {fam_ship} & {c[7]} & {c[8]} & {dcell} \\\\")

    boot = ("Seeded percentile bootstrap over the source sessions "
            "($B{=}1000$, seed 20260708, per-cell hashed sub-streams; the "
            "generated pool is held fixed)")

    tex = HEADER + rf"""
These tables disclose, cell by cell, the behavioral-fidelity evidence
summarized in \S\ref{{sec:behfidelity}}. All numbers are regenerated by the
repository harness (\texttt{{tools/validate\_calibration.py}}); the machine-readable
interval file is \texttt{{docs/experiments/s1\_fidelity\_cis.csv}}. INL is a labeled
fixture and excluded; EV~WATTS uses a port-as-proxy user identity
(\S\ref{{sec:limitations}}).

\begin{{table*}}[tp]
\caption{{Complete S1 per-region marginal fidelity: all {len(s1_rows)}
region$\times$variable cells of the six evaluated sources. Source vs.\
generated moments ($\mu/\sigma$, hours), mean absolute error of the mean
$|\Delta\mu|$, two-sample \ks{{}} and \wone{{}} (hours) with 95\% intervals.
{boot}.}}
\label{{tab:fits-full}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}lllrrrrrrlrl@{{}}}}
\toprule
Source & Region & Var. & $n_{{\mathrm{{src}}}}$ & $n_{{\mathrm{{gen}}}}$ &
src $\mu/\sigma$ & gen $\mu/\sigma$ & $|\Delta\mu|$ &
\ks{{}} & \ks{{}} 95\% CI & \wone{{}} & \wone{{}} 95\% CI \\
\midrule
{chr(10).join(s1_rows)}
\bottomrule
\end{{tabular}}
\end{{table*}}

\begin{{table}}[tbp]
\caption{{S2 joint structure: Spearman $\rho$ of the arrival$\times$dwell
copula, source vs.\ generated, per region ($n$ = source sessions).}}
\label{{tab:fits-copula}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}llrrrr@{{}}}}
\toprule
Source & Region & $n$ & $\rho$ src & $\rho$ gen & gap \\
\midrule
{chr(10).join(s2_rows)}
\bottomrule
\end{{tabular}}
\end{{table}}

\begin{{table*}}[tp]
\caption{{S3 held-out generalization under the family-matched protocol
(\S\ref{{sec:behfidelity}}): distributions are refitted on a deterministic
80/20 driver split (sorted user id) using the same family-selection rule
calibration ships --- a two-component mixture where it beats the single
family by the \ks{{}} margin --- and scored on the unseen drivers.
$\Delta = \ks_{{\text{{holdout}}}} - \ks_{{\text{{train}}}}$; boldface marks
$\Delta \ge 0.19$ (the outlier cells discussed in
\S\ref{{sec:limitations}}, including the three degraded dwell cells).
$\dagger$: the train split's \ks{{}}-margin gate selected a different family
than the full-sample calibration --- protocol-consistent, but not
like-for-like. Because the split is deterministic by user id, large per-cell
$\Delta$ mixes cohort shift and small-sample noise with any true overfit.}}
\label{{tab:fits-heldout}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}lllrrllrrr@{{}}}}
\toprule
Source & Region & Var. & $n_{{\mathrm{{train}}}}$ & $n_{{\mathrm{{test}}}}$ &
refit family & shipped family & \ks{{}} train & \ks{{}} holdout & $\Delta$ \\
\midrule
{chr(10).join(s3_rows)}
\bottomrule
\end{{tabular}}
\end{{table*}}
"""
    (SECTIONS / "appendix_fits.tex").write_text(tex.lstrip())


# --------------------------------------------------------------------------- #
# 2. appendix_corpus.tex
# --------------------------------------------------------------------------- #
WARN_CODES = ("E5", "F4", "F5", "H3", "H7")


def gen_corpus() -> None:
    campus = yaml.safe_load(CAMPUS_YAML.read_text())

    comp_rows = []
    for i, b in enumerate(campus["buildings"], start=1):
        d, o = b["descriptors"], b["overrides"]
        comp_rows.append(
            f"{i} & {esc(d['building'])} & {esc(d['population'])} & "
            f"{esc(d['equipment'])} & {esc(o.get('pv.pv_type', 'none'))} & "
            f"{esc(o.get('battery.battery_type', 'none'))} & "
            f"{b['weather_profile']} & {o['ev_fleet.ev_count']} & "
            f"{b['seed']} \\\\")

    # -- aggregate the ten batch manifests ------------------------------------ #
    warn_rows, totals = [], {c: 0 for c in WARN_CODES}
    grand_units = grand_warned = grand_warnings = grand_failed = 0
    for i in range(1, 11):
        m = json.loads((CAMPUS_DIR / f"b{i}" / "batch_manifest.json").read_text())
        codes = {c: 0 for c in WARN_CODES}
        warned = n_warn = 0
        for s in m["samples"]:
            per_sample = 0
            for u in (s.get("validation") or {}).get("warned_units", []):
                for w in u["warnings"]:
                    code = re.match(r"([A-Z]\d+)", w).group(1)
                    codes[code] += 1
                    per_sample += 1
            n_warn += per_sample
            warned += bool(per_sample)
        assert m["status"] == "succeeded" and m["n_failed"] == 0
        grand_units += m["n_total"]
        grand_failed += m["n_failed"]
        grand_warned += warned
        grand_warnings += n_warn
        for c in WARN_CODES:
            totals[c] += codes[c]
        warn_rows.append(
            f"b{i} & {m['n_succeeded']:,} & {warned:,} & {n_warn:,} & "
            + " & ".join(f"{codes[c]:,}" for c in WARN_CODES) + r" \\")
    total_row = (rf"\midrule Total & {grand_units:,} & {grand_warned:,} & "
                 f"{grand_warnings:,} & "
                 + " & ".join(f"{totals[c]:,}" for c in WARN_CODES) + r" \\")

    unit_files = sorted(
        p.name for p in (CAMPUS_DIR / "b1" / "APR2024" / "0").iterdir())
    file_list = ", ".join(r"\texttt{" + esc(f) + "}" for f in unit_files)

    tex = HEADER + rf"""
This extract accompanies the reference corpus of \S\ref{{sec:release}}: ten
heterogeneous buildings on one campus (San Jose, CA) $\times$ twelve months
(2024) $\times$ 150 samples per building-month --- 18{{,}}000 dataset units,
19.5\,GB. Table~\ref{{tab:corpus-composition}} gives the exact composition
from \texttt{{configs/campus\_10.yaml}}; Table~\ref{{tab:corpus-warnings}} the
complete soft-advisory profile from the ten per-building batch manifests.

\begin{{table*}}[tp]
\caption{{Reference-corpus composition (\texttt{{configs/campus\_10.yaml}}). All
buildings share one site (\texttt{{san\_jose\_ca}}) and the clean noise profile;
sample diversity comes from the per-sample weather realization (slight
$\approx \pm1^{{\circ}}$C~/ $\pm2\%$ solar; moderate $\approx \pm2.5^{{\circ}}$C~/
$\pm5\%$ solar) and the per-sample seed. Charger count equals EV count for
every building. Unit seed = base seed + sample index (0--149); bases are
spaced by 1{{,}}000 so ranges never collide.}}
\label{{tab:corpus-composition}}
\centering\small
\begin{{tabular}}{{@{{}}rllllllrr@{{}}}}
\toprule
\# & Building & Population & Equipment & PV & Battery & Weather & EVs & Base seed \\
\midrule
{chr(10).join(comp_rows)}
\bottomrule
\end{{tabular}}
\end{{table*}}

\begin{{table}}[tbp]
\caption{{Corpus integrity and complete soft-advisory profile, aggregated from
the ten \texttt{{batch\_manifest.json}} files. Every unit passed all hard
invariants (zero errors, zero failed units). Advisory codes
(Appendix~\ref{{app:invariants}}): E5 = charger concurrency near installed
count (a scenario-design property of fully subscribed fleets); F4/F5 =
negotiation-type / behavioral-region share outside the sample-size-aware
$3\sigma$ binomial band (small fleets); H3/H7 = DR program configured (CBP)
but the simulated month produced zero events because the program's
season/trigger conditions were not met.}}
\label{{tab:corpus-warnings}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}lrrrrrrrr@{{}}}}
\toprule
Bldg & Units & Warned & Advisories & E5 & F4 & F5 & H3 & H7 \\
\midrule
{chr(10).join(warn_rows)}
{total_row}
\bottomrule
\end{{tabular}}
\end{{table}}

\paragraph{{Per-unit contents.}}
Each unit is one building-month directory in the shared multi-building
layout (every row tagged with \texttt{{building\_id}}; one campus-wide DSO
command stream per sample): {file_list}. The
\texttt{{multi\_building\_config.json}} in every unit pins the exact resolved
configuration, including the four sampled weather-realization offsets
(dry-bulb, solar, dew-point, wind) and the per-unit validation summary, and
stamps the generator git SHA --- the unit regenerates bitwise from this file
alone.

\paragraph{{Manifest schema note (weather recording).}}
Weather realization is configured \emph{{per building}}, so in this corpus the
batch-level \texttt{{weather\_profile}} field reads \texttt{{none}} and the
authoritative record of each unit's weather draw is the per-unit
configuration file (\S\ref{{sec:release}}). Generator revisions after the
corpus run additionally write a \texttt{{building\_weather\_profiles}} list into
\texttt{{batch\_manifest.json}} --- the effective per-building profile, building
by building --- so the batch manifest is self-describing for future corpora;
the released corpus predates that field and relies on the per-unit record.
"""
    (SECTIONS / "appendix_corpus.tex").write_text(tex.lstrip())


# --------------------------------------------------------------------------- #
# 3. appendix_tstr.tex
# --------------------------------------------------------------------------- #
def _tstr_block(res: dict, label: str) -> list[str]:
    rows = []
    for setting in ("TRTR", "TSTR", "TRTS"):
        m = res[setting]
        rows.append(f"{label} & {setting} & {m['mae']:.2f} & {m['rmse']:.2f} & "
                    f"{m['mape']:.0f} \\\\")
    r = res["TSTR_over_TRTR_ratio"]
    rows.append(rf"{label} & \tstr{{}}/\trtr{{}} & "
                f"{r['mae']:.2f}$\\times$ & {r['rmse']:.2f}$\\times$ & "
                f"{r['mape']:.2f}$\\times$ \\\\")
    return rows


def _series_row(name: str, s: dict) -> str:
    return (f"{name} & {s['n_bins']:,} & {s['start'][:10]} & {s['end'][:10]} & "
            f"{s['mean_kw']:.2f} & {s['peak_kw']:.1f} & {s['total_mwh']:.2f} \\\\")


def gen_tstr() -> None:
    acn = json.loads((TSTR_DIR / "results.json").read_text())
    ela = json.loads((TSTR_DIR / "results_elaadnl_matched.json").read_text())

    acn_rows, ela_rows = [], []
    for res_key, label in (("results_lagged", "lagged, raw"),
                           ("results_calendar_only", "calendar, raw")):
        acn_rows += _tstr_block(acn[res_key], label)
    for res_key, label in (
            ("results_lagged", "lagged, raw"),
            ("results_lagged_normalized", "lagged, norm."),
            ("results_calendar_only", "calendar, raw"),
            ("results_calendar_only_normalized", "calendar, norm.")):
        ela_rows += _tstr_block(ela[res_key], label)

    counts = acn["results_lagged"]["sample_counts"]
    counts_e = ela["results_lagged"]["sample_counts"]
    series_rows = [
        _series_row("ACN real (Caltech 2019--21)", acn["real_series"]),
        _series_row(r"ACN synthetic (S\_acn\_caltech)", acn["synth_series"]),
        _series_row("ElaadNL real (workplace 2020--24)", ela["real_series"]),
        _series_row(r"ElaadNL synthetic (S\_elaadnl\_public\_eu)",
                    ela["synth_series"]),
    ]

    tex = HEADER + rf"""
Full protocol and per-regime results behind Table~\ref{{tab:tstr}}
(\S\ref{{sec:utility}}). Harness:
\texttt{{tools/tstr\_forecasting.py}}; result artifacts:
\texttt{{data/tstr/results.json}} (ACN) and
\texttt{{data/tstr/results\_elaadnl\_matched.json}} (ElaadNL). Both runs use
generator v{acn['generator']['generator_version']} at git
\texttt{{{acn['generator']['generator_git_sha'][:10]}}}, seed
{acn['config']['seed']}.

\paragraph{{Model.}}
A fixed-seed scikit-learn \texttt{{HistGradientBoostingRegressor}}
(\texttt{{max\_iter}}=300, learning rate 0.05, \texttt{{max\_depth}}=6,
\texttt{{min\_samples\_leaf}}=20, $\ell_2$ regularization 1.0,
\texttt{{random\_state}}=1234), predicting one step ahead on the 1-hour
aggregate load series. The harness is one-step-ahead only, so no
per-horizon curves exist; multi-horizon ablations are future work.

\paragraph{{Features and regimes.}}
\emph{{Lagged}}: hour-of-day, day-of-week, and lagged load at $t{{-}}1$,
$t{{-}}2$, $t{{-}}3$, and $t{{-}}24$ bins (the operational forecaster;
partly persistence). \emph{{Calendar-only}}: hour-of-day and day-of-week
only --- with no autoregressive input the model can exploit only the
diurnal/weekly shape learned from its training distribution, so this regime
isolates what the generator's distribution itself contributes.

\paragraph{{Series construction and split.}}
Sessions are converted to an aggregate kW series by the energy-rectangle
proxy: each session's delivered energy is spread at constant power over its
connect$\to$disconnect window, pro-rated by per-bin overlap; the identical
rule is applied to real and synthetic sessions (synthetic delivered energy
is reconstructed from the SoC swing times battery capacity). The real series
is split chronologically 60/40; the last 40\% is the held-out real test set
shared by all three settings (\trtr{{}}, \tstr{{}}, and the TRTS context row,
which trains on real and tests on synthetic). MAPE uses a denominator floor of
5\% of the mean absolute load, and is dominated by near-zero bins on sparse
series --- we report it for completeness but read MAE/RMSE.

\paragraph{{Normalization (shape-transfer variant).}}
Each cohort's series is scaled to unit mean before feature building --- the
real series by its chronological \emph{{train-split}} mean, the synthetic
series by its full-series mean --- so metrics are in per-unit of cohort mean
load. Unlike z-scoring, zeros stay zero, which matters for series with many
empty bins. This removes the magnitude mismatch between a 20-vehicle
synthetic building and a network-scale real aggregate and probes
load-\emph{{shape}} transfer only.

\begin{{table}}[tbp]
\caption{{Cohort scale: the aggregate 1-hour load series entering the
experiment. The ElaadNL pairing is a deliberate cross-scale transfer
(\S\ref{{sec:utility}}).}}
\label{{tab:tstr-series}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}lrllrrr@{{}}}}
\toprule
Series & Bins & Start & End & Mean kW & Peak kW & MWh \\
\midrule
{chr(10).join(series_rows)}
\bottomrule
\end{{tabular}}
\end{{table}}

\begin{{table}}[tbp]
\caption{{ACN-Data: full per-regime results on the held-out real test tail
({counts['real_test']:,} lagged / {acn['results_calendar_only']['sample_counts']['real_test']:,}
calendar-only hourly bins; {counts['real_train']:,} real-train,
{counts['synth']:,} synthetic training bins). Errors in kW.}}
\label{{tab:tstr-acn}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}llrrr@{{}}}}
\toprule
Regime & Setting & MAE & RMSE & MAPE\,\% \\
\midrule
{chr(10).join(acn_rows)}
\bottomrule
\end{{tabular}}
\end{{table}}

\begin{{table}}[tbp]
\caption{{ElaadNL (matched scenario \texttt{{S\_elaadnl\_public\_eu}}): full
per-regime results on the held-out real test tail
({counts_e['real_test']:,} lagged hourly bins; {counts_e['real_train']:,}
real-train, {counts_e['synth']:,} synthetic training bins). Raw rows in kW;
normalized rows in per-unit of cohort mean load.}}
\label{{tab:tstr-elaadnl}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}llrrr@{{}}}}
\toprule
Regime & Setting & MAE & RMSE & MAPE\,\% \\
\midrule
{chr(10).join(ela_rows)}
\bottomrule
\end{{tabular}}
\end{{table}}

\paragraph{{Harness defect, stated fully.}}
The pre-fix harness defaulted its \texttt{{--scenario}} argument to
\texttt{{S\_acn\_caltech}} unconditionally, so an early ElaadNL run silently
paired the ElaadNL real test series with an ACN-calibrated synthetic cohort.
The defective artifact (\texttt{{data/tstr/results\_elaadnl.json}}, generator
git \texttt{{d78d6eeddb}}) is retained in the repository as evidence and is
superseded by \texttt{{results\_elaadnl\_matched.json}}; the fixed harness
derives the default scenario from \texttt{{--real}}. All ElaadNL numbers in
the paper use the matched run.
"""
    (SECTIONS / "appendix_tstr.tex").write_text(tex.lstrip())


# --------------------------------------------------------------------------- #
# 4. appendix_axes.tex
# --------------------------------------------------------------------------- #
AXES_POPS = (  # fitted sources + the hand-specified default, in paper order
    ("acn_workplace_baseline", "ACN-Data, pooled workplace (Caltech + JPL + Office001, 2019--2021)"),
    ("acn_caltech_baseline", "ACN-Data, Caltech site"),
    ("acn_jpl_baseline", "ACN-Data, JPL site"),
    ("acn_office001_baseline", "ACN-Data, Office001 site"),
    ("elaadnl_public_eu", "ElaadNL / 4TU Utrecht workplace (2020--2024)"),
    ("evwatts_workplace_public", "EV WATTS workplace + public L2"),
    ("evwatts_dcfc_public", "EV WATTS public DCFC"),
    ("consent_default", "hand-specified CONSENT-empirical mixed-flex baseline"),
)


def _fmt_bounds(pair: list) -> str:
    return f"$[{pair[0]:g}, {pair[1]:g}]$"


def gen_axes() -> None:
    pops = yaml.safe_load(POPS_YAML.read_text())
    tables = []
    for name, title in AXES_POPS:
        pop = pops[name]
        policy = pop.get("calibration_policy", "synthetic")
        rows = []
        for r in pop["axes_distribution"]:
            rows.append(
                f"{esc(r['name'].replace('_', ' '))} & "
                f"{_fmt_bounds(r['freq'])} & {_fmt_bounds(r['consist'])} & "
                f"{_fmt_bounds(r['dist_km'])} & {r['weight']:g} \\\\")
        tables.append(rf"""
\begin{{table}}[tbp]
\caption{{Region boxes: {title}
(\texttt{{{esc(name)}}}, calibration policy \texttt{{{esc(policy)}}}).}}
\label{{tab:axes-{name.replace('_', '-')}}}
\centering\scriptsize
\begin{{tabular}}{{@{{}}lllll@{{}}}}
\toprule
Region & $\phifreq$ & $\kapcons$ & $\deldist$ (km) & Weight \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{table}}""")

    tex = HEADER + r"""
%% NOTE: full-page matplotlib re-renders of Fig.~\ref{fig:axes} for every
%% source (the assignment scatters) require the git-ignored calibration
%% caches and are not regenerated here; the tables below carry the exact
%% geometries, which is the disclosure the text depends on.
Exact geometries of the behavioral-axes region grids
(\S\ref{sec:calibration}), verbatim from
\texttt{configs/populations.yaml}. Each driver is summarized by plug-in
frequency $\phifreq$, timing consistency $\kapcons$, and daily distance
$\deldist$, and is assigned to the \emph{first} region box containing it
(boxes are checked in table order); $\deldist$ bounds parameterize the
per-region distance prior rather than gating assignment. For fitted
populations the weights are the empirical driver shares of the source corpus
(so they need not be round numbers, and boxes retained for grid completeness
can carry zero weight); for the hand-specified default they are design
choices. The ACN grid predates the re-anchoring procedure applied to ElaadNL
and retains its original geometry (\S\ref{sec:limitations}); the ElaadNL
boxes are anchored on that corpus's empirical $\phifreq$ quantiles, which is
why its $\phifreq$ break-points (0.08, 0.18) differ from the ACN grid's
(0.1, 0.3).
""" + "\n".join(tables) + "\n"
    (SECTIONS / "appendix_axes.tex").write_text(tex.lstrip())


def main() -> None:
    gen_fits()
    gen_corpus()
    gen_tstr()
    gen_axes()
    for f in ("appendix_fits", "appendix_corpus", "appendix_tstr", "appendix_axes"):
        print(f"wrote paper/sections/{f}.tex")


if __name__ == "__main__":
    main()
