#!/usr/bin/env python3
"""Split a multi-building campus config (configs/campus_<TAG>.yaml) into one
single-building config per building, for a BUILDING-MAJOR generation
(each run -> data/output/campus<TAG>/b{i}/<MONTH>/<sample>/), exactly the recipe
used for campus10 (configs/_campus_split/ + tools/run_campus10.sh).

TAG is any suffix: a number ("20", "50") or a name ("10_new").

Usage:  uv run python tools/split_campus_config.py 20 50 10_new
Writes: configs/_campus<TAG>_split/b1.yaml .. b{N}.yaml
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

CONFIGS = Path(__file__).resolve().parents[1] / "configs"
TOP_KEYS = ("output_mode", "emit_sessions_soc", "dr_program",
            "dr_incentive_per_kw", "dr_penalty_per_kwh", "default_policy")


def split(tag: str) -> int:
    src = CONFIGS / f"campus_{tag}.yaml"
    cfg = yaml.safe_load(src.read_text())
    buildings = cfg["buildings"]
    outdir = CONFIGS / f"_campus{tag}_split"
    outdir.mkdir(exist_ok=True)
    # clear any stale split files
    for old in outdir.glob("b*.yaml"):
        old.unlink()
    top = {k: cfg[k] for k in TOP_KEYS if k in cfg}
    for i, b in enumerate(buildings, start=1):
        one = dict(top)
        one["buildings"] = [b]
        text = (f"# {src.name} building {i}/{len(buildings)} — single-building split for a\n"
                f"# building-major generate-multi run into data/output/campus{tag}/b{i}/.\n"
                f"# Auto-generated by tools/split_campus_config.py; edit {src.name} + re-split.\n")
        text += yaml.safe_dump(one, sort_keys=False, default_flow_style=False)
        (outdir / f"b{i}.yaml").write_text(text)
    print(f"campus_{tag}: wrote {len(buildings)} split configs -> {outdir}")
    return len(buildings)


if __name__ == "__main__":
    tags = sys.argv[1:] or ["20", "50"]
    for t in tags:
        split(t)
